/**
 * 
 */
package org.pdks.enums;

public enum PuantajKatSayiTipi {

	AYLIK_HAREKET_BEKLEME_SURESI(1), AYLIK_SUA_GUNLUK_SAAT_SURESI(2), AYLIK_YUVARLAMA_TIPI(3), GUN_OFF_FAZLA_MESAI_TIPI(4), GUN_HT_FAZLA_MESAI_TIPI(5), GUN_ERKEN_GIRIS_TIPI(6), GUN_GEC_CIKIS_TIPI(7), GUN_FMT_DURUM(8), AYLIK_IZIN_HAFTA_TATIL_DURUM(9), GUN_YEMEK_SURE_EKLE_DURUM(10), GUN_ERKEN_CIKIS_TIPI(
			11), GUN_GEC_GIRIS_TIPI(12), AYLIK_FAZLA_MESAI_YUVARLAMA(13), AYLIK_BAYRAM_AYIR(14), AYLIK_CIHAZ_ZAMAN_SANIYE_SIFIRLA(15), GUN_VARDIYA_MOLA(16), AYLIK_IK_MAIL_GONDER(17), AYLIK_YONETICI_MAIL_GONDER(18), AYLIK_UOM_YUVARLAMA(21), AYLIK_RT_YUVARLAMA(22), AYLIK_HT_YUVARLAMA(23), AYLIK_DENKLESTIRME_TIPI(
			24), AYLIK_RADYOLOJI_MAX_GUN(25), AYLIK_RT_KANUNEN_EKLEME(26), GUN_SAAT_CALISAN_GUN(90), GUN_SAAT_CALISAN_NORMAL_GUN(91), GUN_SAAT_CALISAN_IZIN_GUN(92), GUN_SAAT_CALISAN_HAFTA_TATIL(93), GUN_SAAT_CALISAN_RESMI_TATIL(94), GUN_SAAT_CALISAN_ARIFE_NORMAL_SAAT(95), GUN_SAAT_CALISAN_ARIFE_TATIL_SAAT(
			96);

	private final Integer value;

	PuantajKatSayiTipi(Integer v) {
		value = v;
	}

	public Integer value() {
		return value;
	}

	public static PuantajKatSayiTipi fromValue(Integer v) {
		PuantajKatSayiTipi deger = null;
		for (PuantajKatSayiTipi c : PuantajKatSayiTipi.values()) {
			if (c.value.equals(v)) {
				deger = c;
			}
		}
		return deger;
	}

}
