package com.pdks.webservice;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1 2024-02-29T09:04:09.146+02:00 Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://webService.pdks.com/", name = "PdksSoapVeriAktar")
@XmlSeeAlso({ ObjectFactory.class })
public interface PdksSoapVeriAktar {

	/**
	 * PDKS uygulamasi kullanimi içindir
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getERPPersonelList", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetERPPersonelList")
	@WebMethod(action = "urn:GetERPPersonelList")
	@ResponseWrapper(localName = "getERPPersonelListResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetERPPersonelListResponse")
	public List<com.pdks.webservice.PersonelERP> getERPPersonelList(@WebParam(name = "sirketKodu", targetNamespace = "") String sirketKodu, @WebParam(name = "personelNo", targetNamespace = "") String personelNo, @WebParam(name = "basTarih", targetNamespace = "") String basTarih,
			@WebParam(name = "bitTarih", targetNamespace = "") String bitTarih) throws Exception_Exception;

	/**
	 * PDKS uygulamasi kullanimi içindir
	 */
	@WebResult(name = "_return", targetNamespace = "")
	@RequestWrapper(localName = "getFazlaMesaiList", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetFazlaMesaiList")
	@WebMethod(action = "urn:GetFazlaMesaiList")
	@ResponseWrapper(localName = "getFazlaMesaiListResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetFazlaMesaiListResponse")
	public com.pdks.webservice.GetFazlaMesaiListResponse.Return getFazlaMesaiList(@WebParam(name = "mesaiId", targetNamespace = "") List<Long> mesaiId) throws Exception_Exception;

	/**
	 * Bordro uygulamasi PDKS uygulamasindaki fazla mesai bilgileri çeker
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getMesaiPDKS", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetMesaiPDKS")
	@WebMethod(action = "getMesaiPDKS")
	@ResponseWrapper(localName = "getMesaiPDKSResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetMesaiPDKSResponse")
	public List<com.pdks.webservice.MesaiPDKS> getMesaiPDKS(@WebParam(name = "sirketKodu", targetNamespace = "") String sirketKodu, @WebParam(name = "yil", targetNamespace = "") Integer yil, @WebParam(name = "ay", targetNamespace = "") Integer ay,
			@WebParam(name = "donemKapat", targetNamespace = "") Boolean donemKapat, @WebParam(name = "tesisKodu", targetNamespace = "") String tesisKodu) throws Exception_Exception;

	@WebResult(name = "mailStatu", targetNamespace = "")
	@RequestWrapper(localName = "sendMail", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SendMail")
	@WebMethod(action = "urn:SendMail")
	@ResponseWrapper(localName = "sendMailResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SendMailResponse")
	public com.pdks.webservice.MailStatu sendMail(@WebParam(name = "mail", targetNamespace = "") com.pdks.webservice.MailObject mail) throws Exception_Exception;

	/**
	 * Bordro uygulamasindan PDKS uygulamasina senelik izin hakediş aktariminda kullanir. (Sure Birimi : Gun='1'/Saat='2', Zaman format : yyyy-MM-dd HH:mm)
	 * 
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "saveIzinHakedisler", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SaveIzinHakedisler")
	@WebMethod(action = "urn:SaveIzinHakedisler")
	@ResponseWrapper(localName = "saveIzinHakedislerResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SaveIzinHakedislerResponse")
	public List<com.pdks.webservice.IzinHakedis> saveIzinHakedisler(@WebParam(name = "izinHakedis", targetNamespace = "") List<com.pdks.webservice.IzinHakedis> izinHakedis) throws Exception_Exception;

	/**
	 * PDKS uygulamasi kullanimi içindir
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "sendERPIzinler", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SendERPIzinler")
	@WebMethod(action = "urn:SendERPIzinler")
	@ResponseWrapper(localName = "sendERPIzinlerResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SendERPIzinlerResponse")
	public List<com.pdks.webservice.IzinERP> sendERPIzinler(@WebParam(name = "izin", targetNamespace = "") List<com.pdks.webservice.IzinERP> izin) throws Exception_Exception;

	/**
	 * PDKS uygulamasinda Bordro uygulamasindan okunan senelik izin hakedişler için kullanir. (Sure Birimi : Gun='1'/Saat='2', Zaman format : yyyy-MM-dd HH:mm)
	 * 
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getIzinHakedisler", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetIzinHakedisler")
	@WebMethod(action = "urn:GetIzinHakedisler")
	@ResponseWrapper(localName = "getIzinHakedislerResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetIzinHakedislerResponse")
	public List<com.pdks.webservice.IzinHakedis> getIzinHakedisler(@WebParam(name = "personeller", targetNamespace = "") List<String> personeller) throws Exception_Exception;

	/**
	 * Bordro uygulamasindan PDKS uygulamasina personel verisini aktariminda kullanir (Tarih format : yyyy-MM-dd)
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "savePersoneller", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SavePersoneller")
	@WebMethod(action = "urn:SavePersoneller")
	@ResponseWrapper(localName = "savePersonellerResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SavePersonellerResponse")
	public List<com.pdks.webservice.PersonelERP> savePersoneller(@WebParam(name = "personel", targetNamespace = "") List<com.pdks.webservice.PersonelERP> personel) throws Exception_Exception;

	/**
	 * PDKS uygulamasi kullanimi içindir
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "sendFazlaMesaiList", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SendFazlaMesaiList")
	@WebMethod(action = "urn:SendFazlaMesaiList")
	@ResponseWrapper(localName = "sendFazlaMesaiListResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SendFazlaMesaiListResponse")
	public List<com.pdks.webservice.MesaiPDKS> sendFazlaMesaiList(@WebParam(name = "mesaiId", targetNamespace = "") List<Long> mesaiId) throws Exception_Exception;

	/**
	 * Bordro uygulamasindan PDKS uygulamasina izinleri aktariminda kullanir. (Sure Birimi : Gun='1'/Saat='2', Zaman format : yyyy-MM-dd HH:mm)
	 * 
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "saveIzinler", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SaveIzinler")
	@WebMethod(action = "urn:SaveIzinler")
	@ResponseWrapper(localName = "saveIzinlerResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SaveIzinlerResponse")
	public List<com.pdks.webservice.IzinERP> saveIzinler(@WebParam(name = "izin", targetNamespace = "") List<com.pdks.webservice.IzinERP> izin) throws Exception_Exception;
}
