package com.pdks.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1 2020-11-15T20:22:32.142+02:00 Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://webService.pdks.com/", name = "PdksSoapVeriAktar")
@XmlSeeAlso({ ObjectFactory.class })
public interface PdksSoapVeriAktar {

	/**
	 * PDKS uygulaması kullanımı içindir
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getERPPersonelList", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetERPPersonelList")
	@WebMethod(action = "urn:GetERPPersonelList")
	@ResponseWrapper(localName = "getERPPersonelListResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetERPPersonelListResponse")
	public java.util.List<com.pdks.webservice.PersonelERP> getERPPersonelList(@WebParam(name = "sirketKodu", targetNamespace = "") java.lang.String sirketKodu, @WebParam(name = "personelNo", targetNamespace = "") java.lang.String personelNo,
			@WebParam(name = "basTarih", targetNamespace = "") java.lang.String basTarih, @WebParam(name = "bitTarih", targetNamespace = "") java.lang.String bitTarih) throws Exception_Exception;

	/**
	 * PDKS uygulaması kullanımı içindir
	 */
	@WebResult(name = "_return", targetNamespace = "")
	@RequestWrapper(localName = "getFazlaMesaiList", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetFazlaMesaiList")
	@WebMethod(action = "urn:GetFazlaMesaiList")
	@ResponseWrapper(localName = "getFazlaMesaiListResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetFazlaMesaiListResponse")
	public com.pdks.webservice.GetFazlaMesaiListResponse.Return getFazlaMesaiList(@WebParam(name = "mesaiId", targetNamespace = "") java.util.List<java.lang.Long> mesaiId) throws Exception_Exception;

	/**
	 * Bordro uygulaması PDKS uygulamasındaki fazla mesai bilgileri çeker
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getMesaiPDKS", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetMesaiPDKS")
	@WebMethod(action = "getMesaiPDKS")
	@ResponseWrapper(localName = "getMesaiPDKSResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.GetMesaiPDKSResponse")
	public java.util.List<com.pdks.webservice.MesaiPDKS> getMesaiPDKS(@WebParam(name = "sirketKodu", targetNamespace = "") java.lang.String sirketKodu, @WebParam(name = "yil", targetNamespace = "") java.lang.Integer yil, @WebParam(name = "ay", targetNamespace = "") java.lang.Integer ay,
			@WebParam(name = "donemKapat", targetNamespace = "") java.lang.Boolean donemKapat) throws Exception_Exception;

	@WebResult(name = "mailStatu", targetNamespace = "")
	@RequestWrapper(localName = "sendMail", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SendMail")
	@WebMethod(action = "urn:SendMail")
	@ResponseWrapper(localName = "sendMailResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SendMailResponse")
	public com.pdks.webservice.MailStatu sendMail(@WebParam(name = "mail", targetNamespace = "") com.pdks.webservice.MailObject mail) throws Exception_Exception;

	/**
	 * PDKS uygulaması kullanımı içindir
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "sendERPIzinler", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SendERPIzinler")
	@WebMethod(action = "urn:SendERPIzinler")
	@ResponseWrapper(localName = "sendERPIzinlerResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SendERPIzinlerResponse")
	public java.util.List<com.pdks.webservice.IzinERP> sendERPIzinler(@WebParam(name = "izin", targetNamespace = "") java.util.List<com.pdks.webservice.IzinERP> ızin) throws Exception_Exception;

	/**
	 * Bordro uygulamasından PDKS uygulamasına personel verisini aktarımında kullanır (Tarih format : yyyy-MM-dd)
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "savePersoneller", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SavePersoneller")
	@WebMethod(action = "urn:SavePersoneller")
	@ResponseWrapper(localName = "savePersonellerResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SavePersonellerResponse")
	public java.util.List<com.pdks.webservice.PersonelERP> savePersoneller(@WebParam(name = "personel", targetNamespace = "") java.util.List<com.pdks.webservice.PersonelERP> personel) throws Exception_Exception;

	/**
	 * PDKS uygulaması kullanımı içindir
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "sendFazlaMesaiList", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SendFazlaMesaiList")
	@WebMethod(action = "urn:SendFazlaMesaiList")
	@ResponseWrapper(localName = "sendFazlaMesaiListResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SendFazlaMesaiListResponse")
	public java.util.List<com.pdks.webservice.MesaiPDKS> sendFazlaMesaiList(@WebParam(name = "mesaiId", targetNamespace = "") java.util.List<java.lang.Long> mesaiId) throws Exception_Exception;

	/**
	 * Bordro uygulaması PDKS uygulamasını izinleri aktarımında kullanır. (Sure Birimi : Gun='1'/Saat='2', Zaman format : yyyy-MM-dd HH:mm)
	 */
	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "saveIzinler", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SaveIzinler")
	@WebMethod(action = "urn:SaveIzinler")
	@ResponseWrapper(localName = "saveIzinlerResponse", targetNamespace = "http://webService.pdks.com/", className = "com.pdks.webservice.SaveIzinlerResponse")
	public java.util.List<com.pdks.webservice.IzinERP> saveIzinler(@WebParam(name = "izin", targetNamespace = "") java.util.List<com.pdks.webservice.IzinERP> ızin) throws Exception_Exception;
}
