package com.pdks.webservice;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.6.1 2020-03-09T15:54:38.776+02:00 Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "PdksSoapVeriAktarService", targetNamespace = "http://webService.pdks.com/")
public class PdksSoapVeriAktarService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://webService.pdks.com/", "PdksSoapVeriAktarService");
	public final static QName PdksSoapVeriAktarPort = new QName("http://webService.pdks.com/", "PdksSoapVeriAktarPort");
	static {
		URL url = null;
		url = PdksSoapVeriAktarService.class.getClassLoader().getResource("wsdl/pdksSoapVeriAktar.wsdl");

		WSDL_LOCATION = url;
	}

	public PdksSoapVeriAktarService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public PdksSoapVeriAktarService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PdksSoapVeriAktarService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return returns PdksSoapVeriAktar
	 */
	@WebEndpoint(name = "PdksSoapVeriAktarPort")
	public PdksSoapVeriAktar getPdksSoapVeriAktarPort() {
		return super.getPort(PdksSoapVeriAktarPort, PdksSoapVeriAktar.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their default values.
	 * @return returns PdksSoapVeriAktar
	 */
	@WebEndpoint(name = "PdksSoapVeriAktarPort")
	public PdksSoapVeriAktar getPdksSoapVeriAktarPort(WebServiceFeature... features) {
		return super.getPort(PdksSoapVeriAktarPort, PdksSoapVeriAktar.class, features);
	}

}
